128 threads
klitsunova/TrenchWar pull request #129
Opened 2022-07-08 21:18 UTC by AzyavchikovAlex

2022-07-09 07:58 UTC, Dima-Makarov commented on TrenchWar/Models/world.cpp
> +  distance_loading_threads_.push(std::move(thread));
Какое-то дублирование

2022-07-09 12:03 UTC, dasfex requested changes

2022-07-09 12:03 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +  std::thread thread([&](QPoint pos) {
Давай не будем всё по ссылке захватывать.

2022-07-09 12:03 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +  distance_loading_threads_.push(std::move(thread));
Можно не создавать поток, а потом его мувать, а передавать лямбду и аргументы для потока в очередь через emplace.

2022-07-09 12:03 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +  distance_loading_threads_.push(std::move(thread));
Same shit.

2022-07-09 12:03 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +          - Settings::kMinVolume));
Две строчки поместятся в одну. Не надо разносить.

2022-07-09 12:03 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +  distances_mutex_.unlock();
Можно в начале функции заюзать std::lock_guard, чтобы не анлочить самому.

2022-07-09 12:03 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +            (type == "kAttacker" && side == Side::kDefender))) {
Строковые значение можно в константу вынести. Сто процентов они где-то ещё юзаются.

2022-07-09 12:03 UTC, dasfex commented on TrenchWar/Models/world.cpp
>    for (int i = 0; i < cells_.size(); ++i) {
А почему тут int, но сравнивается с size_t? Это ж ворнинг, значит не должно компилироваться.

2022-07-09 12:03 UTC, dasfex commented on TrenchWar/Models/world.cpp
>                            std::vector<int>(cells_[0].size(), INT32_MAX));
Вместо INT32_MAX надо std::numeric_limits.

2022-07-09 12:03 UTC, dasfex commented on TrenchWar/Models/world.h
> +  void GenerateNewDistances(QPoint pos);
А что это ты?)
Можно же в поток по ссылке передавать (std::ref).

2022-07-14 08:36 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +  distance_loading_threads_.push(std::move(thread));
+

2022-07-14 08:38 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +  distance_loading_threads_.push(std::move(thread));
Вообще, стоит поработать с функцией AddTower() и избежать хронического дублирования кода в ней и AddTower(const QPoint&). Я вынесу это в отдельный пр.

2022-07-14 08:38 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +  std::thread thread([&](QPoint pos) {
+

2022-07-14 08:38 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +  distance_loading_threads_.push(std::move(thread));
+

2022-07-14 08:38 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +  distance_loading_threads_.push(std::move(thread));
+

2022-07-14 08:44 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.h
> +  void GenerateNewDistances(QPoint pos);
+

2022-07-14 08:46 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
>                            std::vector<int>(cells_[0].size(), INT32_MAX));
+

2022-07-14 08:47 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +          - Settings::kMinVolume));
+

2022-07-14 08:47 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +  distances_mutex_.unlock();
+

2022-07-14 08:48 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +            (type == "kAttacker" && side == Side::kDefender))) {
как?

2022-07-14 08:48 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
>    for (int i = 0; i < cells_.size(); ++i) {
всегда так делал, всё работает. а как иначе?

2022-07-14 19:58 UTC, dasfex commented on TrenchWar/Models/world.cpp
>    for (int i = 0; i < cells_.size(); ++i) {
Ну оно-то работает, но это не норм)
Писать size_t i = 0.

2022-07-14 19:59 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +            (type == "kAttacker" && side == Side::kDefender))) {
А что не понятно?

2022-08-03 07:43 UTC, dasfex approved these changes

2022-08-03 18:00 UTC, Dima-Makarov approved these changes

2022-08-03 21:20 UTC, merged