107 create json parser
klitsunova/TrenchWar pull request #135
Opened 2022-08-19 22:30 UTC by DaniilDomnin

2022-08-20 17:59 UTC, AzyavchikovAlex commented on MapGenerator/map_generator.cpp
> +                 QJsonValue::fromVariant(static_cast<int>(map_.size())));
Давай везде уберем QJsonValue::fromVariant(...) . Без него вроде тоже работает

2022-08-20 17:59 UTC, AzyavchikovAlex commented on MapGenerator/map_generator.cpp
> +  std::stringstream map_string;
Предлагаю использовать сразу QString и дальше вместо << писать string+="some text"

2022-08-20 17:59 UTC, AzyavchikovAlex commented on TrenchWar/Views/Game/buy_window.cpp
> +  QJsonArray pos = obj["Positions"].toArray();
Предлагаю pos назвать positions - более интуитивно

2022-08-20 17:59 UTC, AzyavchikovAlex commented on TrenchWar/Views/Game/buy_window.cpp
> +    QPixmap pixmap(element["filename"].toString());
Возможно ли здесь пользоваться pixmap_loader, чтобы при открытии окна каждый раз не загружать картинку?

2022-08-20 17:59 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +  QJsonObject j_size  = obj.value("Size").toObject();
предлагаю убрать j в названии j-son object: компилятор и так знает, что это QJsonObject, а при чтении занимает место

2022-08-20 17:59 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +  QJsonArray j_color_value = obj["Colors and speed"].toArray();
предлагаю переименовать j_color_value в color_speed_values

2022-08-20 17:59 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +  std::stringstream st(obj["Map"].toString().toStdString());
Предлагаю воспользоваться примерно следующей конструкцией:
QString str = "10 11  20   30";
QTextStream stream(&str);
int x;
stream >> x;

Таким образом заменив std::stringstream на QTextStream

2022-08-20 18:46 UTC, DaniilDomnin commented on MapGenerator/map_generator.cpp
> +                 QJsonValue::fromVariant(static_cast<int>(map_.size())));
*

2022-08-20 18:46 UTC, DaniilDomnin commented on MapGenerator/map_generator.cpp
> +  std::stringstream map_string;
*

2022-08-20 18:46 UTC, DaniilDomnin commented on TrenchWar/Views/Game/buy_window.cpp
> +  QJsonArray pos = obj["Positions"].toArray();
*

2022-08-20 18:46 UTC, DaniilDomnin commented on TrenchWar/Models/world.cpp
> +  QJsonObject j_size  = obj.value("Size").toObject();
*

2022-08-20 18:46 UTC, DaniilDomnin commented on TrenchWar/Models/world.cpp
> +  QJsonArray j_color_value = obj["Colors and speed"].toArray();
*

2022-08-20 18:46 UTC, DaniilDomnin commented on TrenchWar/Models/world.cpp
> +  std::stringstream st(obj["Map"].toString().toStdString());
*

2022-08-20 18:48 UTC, DaniilDomnin commented on TrenchWar/Views/Game/buy_window.cpp
> +    QPixmap pixmap(element["filename"].toString());
Не знаю, это было написано до меня, я просто загрузку из json добавил

2022-08-20 18:59 UTC, AzyavchikovAlex commented on TrenchWar/Views/Game/buy_window.cpp
> +    QPixmap pixmap(element["filename"].toString());
Предлагаю использовать: PixmapLoader::GetPixmap

PixmapLoader::GetPixmap(element["filename"].toString())

2022-08-20 19:09 UTC, DaniilDomnin commented on TrenchWar/Views/Game/buy_window.cpp
> +    QPixmap pixmap(element["filename"].toString());
*

2022-08-20 19:10 UTC, AzyavchikovAlex submitted a review, later dismissed

2022-08-21 15:25 UTC, dasfex requested changes

2022-08-21 15:25 UTC, dasfex commented on MapGenerator/map_generator.cpp
>  #include "map_generator.h"
Сначала главный хедер, а потом остальные.

2022-08-21 15:25 UTC, dasfex commented on MapGenerator/map_generator.cpp
> +
Это что..

2022-08-21 15:25 UTC, dasfex commented on TrenchWar/Models/world.cpp
>  #include <QAudioOutput>
Давай пустую строку между группами.

2022-08-21 15:25 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +  width = size["Width"].toInt();
Можно переменные лучше сразу инициализировать. Неинициализированные переменные это потенциальная уязвимость. 

Ну и каждую переменную в своей строк объявлять.

2022-08-21 15:25 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +    color_and_value.emplace_back(color, speed);
Range based for.

2022-08-21 15:25 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +  auto add_soldier = [&](const QJsonArray& array) {
Не надо всё захватывать. Указывай только нужное.

2022-08-21 15:25 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +    for (const auto & i : array) {
Пробел перед & не надо. Настрой линтеры пж.

2022-08-21 15:25 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +    for (const auto & i : array) {
Ну и имя переменной какое-то более говорящее.

2022-08-21 15:25 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +    int x, y;
Эти переменные тут не нужны.

2022-08-21 15:25 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +  int x, y;
Инициализировать. И каждую в своей строке.

2022-08-21 15:25 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +  int x, y;
Видимо их в цикл можно занести.

2022-08-21 15:25 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +  for (auto && terrain_object : terrain_objects) {
А зачем тут &&?

2022-08-21 15:25 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +  for (auto && terrain_object : terrain_objects) {
И пробел.

2022-08-21 15:25 UTC, dasfex commented on TrenchWar/Views/Game/buy_window.cpp
> +  for (auto && position : positions) {
&& и пробел?

2022-08-21 15:25 UTC, dasfex commented on TrenchWar/Views/Game/buy_window.cpp
> +    auto* item = new QListWidgetItem;
Родителя не указал. Память не потечёт?

2022-08-21 15:31 UTC, Dima-Makarov commented on TrenchWar/Models/world.cpp
>  #include <QAudioOutput>
ААААААА ДА ХВАТИТ ПИСАТЬ КОММЕНТЫ НА ИНКЛЮДЫ

@DaniilDomnin ААААА ДА НАСТРОЙ УЖЕ СЕБЕ ЛИНТЕР НА ИНКЛЮДЫ

2022-08-21 15:32 UTC, Dima-Makarov commented on TrenchWar/Models/world.cpp
> +    color_and_value.emplace_back(color, speed);
Based.

2022-08-21 15:36 UTC, DaniilDomnin commented on MapGenerator/map_generator.cpp
>  #include "map_generator.h"
*

2022-08-21 15:36 UTC, DaniilDomnin commented on MapGenerator/map_generator.cpp
> +
*

2022-08-21 15:37 UTC, DaniilDomnin commented on TrenchWar/Models/world.cpp
> +  width = size["Width"].toInt();
*

2022-08-21 15:38 UTC, DaniilDomnin commented on TrenchWar/Models/world.cpp
> +    color_and_value.emplace_back(color, speed);
*

2022-08-21 15:39 UTC, DaniilDomnin commented on TrenchWar/Models/world.cpp
> +    for (const auto & i : array) {
*

2022-08-21 15:39 UTC, DaniilDomnin commented on TrenchWar/Models/world.cpp
> +    int x, y;
*

2022-08-21 15:39 UTC, DaniilDomnin commented on TrenchWar/Models/world.cpp
> +  int x, y;
*

2022-08-21 15:41 UTC, DaniilDomnin commented on TrenchWar/Models/world.cpp
> +  for (auto && terrain_object : terrain_objects) {
Пробел убрал, без && Non-const lvalue reference to type 'QJsonValueRef' cannot bind to a temporary of type 'QJsonValueRef'

2022-08-21 15:41 UTC, DaniilDomnin commented on TrenchWar/Views/Game/buy_window.cpp
> +  for (auto && position : positions) {
*

2022-08-21 15:41 UTC, DaniilDomnin commented on TrenchWar/Views/Game/buy_window.cpp
> +    auto* item = new QListWidgetItem;
*

2022-08-21 15:49 UTC, DaniilDomnin commented on TrenchWar/Models/world.cpp
> +  auto add_soldier = [&](const QJsonArray& array) {
*

2022-08-21 15:50 UTC, DaniilDomnin commented on TrenchWar/Models/world.cpp
>  #include <QAudioOutput>
*

2022-10-24 10:58 UTC, AzyavchikovAlex approved these changes

2022-10-24 15:53 UTC, dasfex approved these changes

2022-10-24 15:54 UTC, merged