134 no need in zombie
klitsunova/TrenchWar pull request #136
Opened 2022-08-20 18:01 UTC by AzyavchikovAlex

2022-08-21 15:34 UTC, dasfex requested changes

2022-08-21 15:34 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +                                    --distances_.end(),
Не нравится мне такое что-то. 
Там точно надо итератор принимать? Мб можно на объект переделать и передавать back()?

2022-08-21 15:34 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +    for (auto& distance : distances_) {
const auto&.

2022-08-21 15:34 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +  auto MoveIf = [&](const std::shared_ptr<Soldier>& soldier, int& current_dist,
Не захватывать по ссылке всё.

2022-08-21 15:34 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +  auto IssueCommand = [&](const std::shared_ptr<Soldier>& soldier,
Не захватывать по ссылке всё.

2022-08-21 15:34 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +    cells_[y][x].soldiers.insert(*soldier);
Не оч постоянно разыменовывать итератор. Либо в начале ссылку на *soldier в переменную, либо лучше range based for. 

Если начинаете дублировать код, задумайтесь, всё ли правильно вы делаете.

2022-08-21 15:34 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +        bullets_.erase(bullet_for_possible_delete);
Тут тож разыменовывание итератора в переменную можно.

2022-08-21 15:34 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +    ++bullet;
Почему нельзя инкремент в цикле оставить? bullet ниже не юзается, т.е. разницы нет.

2022-08-21 15:34 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +    ++soldier;
Аналогично с инкрементом.

2022-08-21 15:34 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +    ++bullet;
А. Наверн итераторы инвалидируются, да? Надо подумать что-то, мне не оч нрав.

2022-08-21 15:34 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +          if ((*soldier)->GetSide() == Side::kAttacker) {
Аналогично с разыменовыванием.

2022-08-21 15:34 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +  for (; tower != towers_.end();) {
Это называется while : )

2022-08-21 15:34 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +  for (; tower != towers_.end();) {
Точно for нельзя нормально заюзать?

2022-08-21 15:34 UTC, dasfex commented on TrenchWar/Models/world.cpp
>        is_need_update_towers_ = true;
Так может удалить?

2022-08-21 16:41 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +    ++bullet;
Да, возникает проблема удаления текущего: для этого сохраняется текущая позиция, а указатель смещается, и если нужно удалить - удаляем сохранение

2022-08-24 07:01 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
>        is_need_update_towers_ = true;
+

2022-08-24 07:01 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +          if ((*soldier)->GetSide() == Side::kAttacker) {
+

2022-08-24 07:01 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +                                    --distances_.end(),
+

2022-08-24 07:01 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +    for (auto& distance : distances_) {
+

2022-08-24 07:01 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +  auto MoveIf = [&](const std::shared_ptr<Soldier>& soldier, int& current_dist,
+

2022-08-24 07:02 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +  auto IssueCommand = [&](const std::shared_ptr<Soldier>& soldier,
+

2022-08-24 07:02 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +    cells_[y][x].soldiers.insert(*soldier);
+

2022-08-24 07:02 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +        bullets_.erase(bullet_for_possible_delete);
+

2022-08-25 18:04 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +  for (; tower != towers_.end();) {
нет, вроде

2022-08-26 11:28 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +    ++bullet;
Ну тогда норм. Только я бы имя покороче сделал. Имхо лучше опускать предлоги (смысл никуда не теряется): maybe_deleted_bullet например.

2022-08-26 11:28 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +    ++soldier;
Аналогично с именем.

2022-08-26 11:30 UTC, dasfex requested changes

2022-08-26 11:30 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +  for (; tower != towers_.end();) {
Ну тогда на while переделать.

2022-08-26 11:30 UTC, dasfex commented on TrenchWar/Models/world.cpp
> +      (*tower)->TakeDamage(soldier->GetTowerDamage());
Опять разыменовывание в переменную можно.

2022-08-26 17:49 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +      (*tower)->TakeDamage(soldier->GetTowerDamage());
+

2022-08-26 17:49 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +  for (; tower != towers_.end();) {
+

2022-08-26 17:49 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +    ++soldier;
+

2022-08-26 17:49 UTC, AzyavchikovAlex commented on TrenchWar/Models/world.cpp
> +    ++bullet;
+

2022-08-26 18:00 UTC, dasfex submitted a review, later dismissed

2022-09-01 06:30 UTC, DaniilDomnin approved these changes, later dismissed

2022-10-22 21:01 UTC, dasfex approved these changes

2022-10-22 21:06 UTC, DaniilDomnin approved these changes

2022-10-23 07:15 UTC, merged